# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-28 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pieflyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='playerName',
            field=models.CharField(default='Anonymous Player', max_length=200),
        ),
        migrations.AddField(
            model_name='score',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
